### ISSUE TITLE
Need a logo for the library.

### ISSUE THREAD

**Issue by Gautam-Arora24** [Gautam-Arora24/nixty#1]
We need some sort of logo for the library. So, if you are a Graphic designer and wanted to contribute to the open source community then here's your good chance.

**Comment by oneamanish** [comment]
see my pull req.

**Comment by SaxenaAnushka102** [comment]
Hello @Gautam-Arora24! I'd like to contribute, could you please assign this to me?

**Comment by Gautam-Arora24** [comment]
Hi @SaxenaAnushka102! Sure!

**Comment by SaxenaAnushka102** [comment]
Hey @Gautam-Arora24 I'm on it! Could you please provide some information about the theme, required picture resolution & dimension details?

**Comment by Gautam-Arora24** [comment]
We'll be using the logo in the `README.md` file so you can make something that extends till the whole width of the file.

**Comment by SaxenaAnushka102** [comment]
Hi @Gautam-Arora24! I've done a PR, please check it out.

**Comment by Gautam-Arora24** [comment]
@SaxenaAnushka102 You have pointed your PR to the wrong origin(your own repo), please point it towards `Gautam-Arora24/nixty`.

**Comment by SaxenaAnushka102** [comment]
Sorry, did that by mistake. I've corrected now.

**Comment by Gautam-Arora24** [comment]
Closes with #3
